"""
SaveSync - Core Constants
Centralized configuration to avoid hardcoding.
"""
from pathlib import Path
import os
import platform

# App identity
APP_NAME = "SaveSync"
APP_VERSION = "1.2.2"
APP_ID = "com.savesync.app"

# Paths — platform-aware data directory
def _user_data_dir() -> Path:
    system = platform.system()
    if system == "Windows":
        return Path(os.getenv("APPDATA", str(Path.home()))) / APP_NAME
    elif system == "Darwin":
        return Path.home() / "Library" / "Application Support" / APP_NAME
    else:
        return Path(os.getenv("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))) / APP_NAME

USER_DATA_DIR = _user_data_dir()
CONFIG_FILE = USER_DATA_DIR / "config.json"
LIBRARY_FILE = USER_DATA_DIR / "library.json"
BACKUP_DIR = USER_DATA_DIR / "backups"
LOGS_DIR = USER_DATA_DIR / "logs"
CACHE_DIR = USER_DATA_DIR / "cache"
MACHINE_ID_FILE = USER_DATA_DIR / "machine_id"
CONFIG_HISTORY_DIR = USER_DATA_DIR / "config_history"

def _with_plural_list(words) -> list[str]:
    """Ordered, de-duplicated expansion of *words* with their simple English
    plural (trailing 's'), first-seen order preserved. Lets a keyword list
    name each word once instead of both forms by hand ("save" also yields
    "saves", "profile"→"profiles"); a word already ending in 's' is emitted
    unchanged. List form for call sites that iterate or extend the result."""
    out: list[str] = []
    for w in words:
        wl = (w or "").lower()
        if not wl or wl in out:
            continue
        out.append(wl)
        if not wl.endswith('s'):
            pl = wl + 's'
            if pl not in out:
                out.append(pl)
    return out


# Save detection - folders that commonly contain save data (not hardcoded,
# user can extend). Listed as singulars; the plural forms ("save"→"saves",
# "profile"→"profiles", "backup"→"backups", …) are generated by the
# trailing-s combinator so no form is ever typed twice.
SAVE_FOLDER_HINTS = _with_plural_list([
    "save", "savegame", "save_game", "savedata", "save_data",
    "gamesave", "game_save", "progress", "userdata", "user_data",
    "profile", "slot", "checkpoint", "autosave", "quicksave",
    "backup", "data",
])

# Windows paths to watch (not hardcoded; resolved at runtime)
# Covers: Unity (LocalLow), Unreal (AppData/Local + Saved), old-school (Documents),
# Steam (userdata), GOG (AppData/Roaming), Windows Store (LocalLow), etc.
WATCH_PATHS_TEMPLATES = [
    # AppData — Roaming (most Windows games: config, saves in company subfolders)
    "{APPDATA}",
    # AppData — Local (Unreal Engine "Saved" folders, many indie games)
    "{LOCALAPPDATA}",
    # AppData — LocalLow (Unity default: Application.persistentDataPath on Windows)
    "{USERPROFILE}/AppData/LocalLow",
    # Documents (classic location: EA, Rockstar, Bethesda, many others).
    # Game-specific subfolders are covered by the "My Games" root — do not
    # list individual titles here.
    "{USERPROFILE}/Documents",
    "{USERPROFILE}/Documents/My Games",
    "{USERPROFILE}/Documents/Electronic Arts",
    "{USERPROFILE}/Documents/Rockstar Games",
    # Saved Games (Windows shell folder, used by some titles)
    "{USERPROFILE}/Saved Games",
    # Steam userdata (cloud-ready saves — under steam install, but also replicated locally)
    "{LOCALAPPDATA}/Steam",
    # OneDrive synced saves
    "{USERPROFILE}/OneDrive/Documents/My Games",
    "{USERPROFILE}/OneDrive/Documents",
    # Linux / macOS equivalents resolved at runtime by _resolve_watch_paths()
]

# File extensions to skip during save scanning.
# NOTE: keep this list narrow — many games use .sav, .save, .ini, .cfg, .xml
# as their actual save format. Only skip clearly non-save content.
SKIP_EXTENSIONS = {
    ".exe", ".dll", ".so", ".pak", ".rpa",
    ".log", ".pdb", ".lib", ".obj",
    ".mp3", ".ogg", ".wav", ".flac",
    ".png", ".jpg", ".jpeg", ".bmp", ".tga", ".dds",
    ".mp4", ".avi", ".mkv",
    ".ttf", ".otf",
    ".hlsl", ".glsl", ".shader",
    ".assets", ".unity", ".unity3d",
    ".py", ".pyc", ".pyo",
    ".info", ".html", ".htm",
    ".txt",
}


def _with_simple_plural(words) -> frozenset:
    """Frozenset form of the trailing-s plural combinator (see
    _with_plural_list): "log" also covers "logs" without a separate entry.
    Used by exclusion sets that need set-membership (e.g. SKIP_FILENAME_STEMS)."""
    return frozenset(_with_plural_list(words))


# Filenames (stem only — extension ignored) that should never be detected
# or backed up as save data, regardless of their extension: a "log" file
# living next to real saves (log.txt, log.dat, or extension-less) is engine
# noise, not player data. Only the singular needs to be listed; see
# _with_simple_plural() above for the "log"/"logs" combinator.
SKIP_FILENAME_STEMS = _with_simple_plural({
    "log",
    "cache",
})

# Extensions excluded from save DETECTION only (scan scoring, live tracking,
# watcher events, auto-scan proposals). Deliberately NOT merged into the
# backup skip list: a user-confirmed save folder may legitimately contain
# .dat/.bin saves and those must keep being backed up — they just must not
# drive automatic detection, where they are overwhelmingly engine noise.
DETECTION_SKIP_EXTENSIONS = {
    ".info", ".html", ".htm", ".dat", ".bin",
}

# Machine fingerprint fields — used by machine.py to build identity hash
MACHINE_FIELDS = ["node", "processor", "machine", "system"]

# Backup fallbacks (runtime values live in config_manager._DEFAULTS)
MAX_LOCAL_BACKUPS = 6
BACKUP_RETENTION_DAYS = 30
MIN_KEPT_BACKUPS = 3


# Insert-a-space camelCase boundary ("SuperGameStory" → "Super Game Story").
# Shared by the search/query builders, the save detector and the scan dialog.
CAMEL_SPLIT_RE = r'(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])'


def strip_version_tokens(name: str) -> str:
    """Remove version/build markers and DLsite product codes from a
    game/folder name: ``v1.2``, ``V0.5.3b``, ``ver 2``, ``version 3.0``,
    ``b12``, ``build 15``, ``Build-2024.1``, ``[RJ123456]``/``RE``/``VJ``
    codes — these change across game updates or disappear on other
    stores while the game stays the same, so identity comparisons
    (remote backup folders, search queries) must ignore them. The code
    prefixes are the DLsite product-code family ((RJ|RE|VJ) + 4-10 digits).

    Bare numbers and roman numerals are deliberately preserved:
    "Example Game 3", "Example Game V" and "Example Game RE4" keep their
    sequel identity (version markers must be followed by digits; DLsite
    codes need at least 4 digits).
    """
    import re
    if not name:
        return name
    # (?<![a-zA-Z0-9]) instead of \b: underscores are word chars, so \b never
    # fires in names like "MyGame_v0.5_build12". The trailing
    # (?![a-zA-Z0-9]) keeps tokens whole: "V2ray" and "RJ123456abc" are
    # names, not markers; "v0.5b" (single letter suffix) is still one.
    cleaned = re.sub(
        r'[\s._\-\(\[]*(?<![a-zA-Z0-9])'
        r'(?:(?:v(?:er(?:sion)?)?|b(?:uild)?)[\s._\-]*\d+(?:[._\-]\d+)*[a-z]?'
        r'|(?:RJ|RE|VJ)\d{4,10})'
        r'(?![a-zA-Z0-9])[\)\]]*',
        ' ', name, flags=re.IGNORECASE,
    )
    cleaned = re.sub(r'\s{2,}', ' ', cleaned).strip(' ._-')
    return cleaned or name


# The kana voiced/semi-voiced sound marks. Combining characters, but part of
# the letter rather than an accent on it — see match_slug.
_KANA_VOICING = ("゙", "゚")


def match_slug(name: str) -> str:
    """A name reduced to its letters and digits, for comparing two names.

    Keeps letters and digits in ANY script, which is the whole point. The
    rule this replaces was ``[^a-z0-9]`` — it deleted every character that
    was not a plain ASCII letter or digit, so a title written entirely in
    Japanese, Chinese, Korean, Russian or Greek slugged down to the empty
    string and could never be matched against the folder it saves into,
    however exactly the two names agreed.

    Accents are FOLDED rather than kept, and that is not a detail. A game
    called ``Café`` very often installs into a folder called ``Cafe``, and a
    slug that kept the accent would stop matching the two — worse than the
    rule it replaces, which at least reduced both to something shared. So
    the name is decomposed and its combining marks dropped first: ``Café``
    and ``Cafe`` both become ``cafe``. Full-width and ligature forms fold the
    same way, which is what NFKD is for.

    Japanese voicing marks are the one exception, and they have to be. A
    dakuten is a combining mark like an acute accent is, but it is not
    decoration: ``ゲ`` and ``ケ`` are different kana, the way ``b`` and ``p``
    are different letters. Dropping it with the accents would fold apart
    games that merely sound alike, so it is kept and put back.

    ASCII names come out exactly as they did before.
    """
    import unicodedata
    text = unicodedata.normalize("NFKD", (name or "").lower())
    kept = "".join(ch for ch in text
                   if ch in _KANA_VOICING or not unicodedata.combining(ch))
    return "".join(ch for ch in unicodedata.normalize("NFC", kept)
                   if ch.isalnum())


# Scripts that pack a word into far fewer characters than Latin does: the
# kana, the CJK ideographs, and the hangul syllables. Used by slug_weight.
_DENSE_SCRIPTS = (
    (0x3040, 0x30FF),   # hiragana and katakana
    (0x3400, 0x4DBF),   # CJK unified ideographs, extension A
    (0x4E00, 0x9FFF),   # CJK unified ideographs
    (0xF900, 0xFAFF),   # CJK compatibility ideographs
    (0xAC00, 0xD7AF),   # hangul syllables
)


def slug_weight(slug: str) -> int:
    """How distinctive a slug is, measured in Latin-equivalent characters.

    Every "is this name specific enough to match on?" test used to count
    characters, which was the same thing as counting Latin letters because a
    slug could not hold anything else. Now that it can, counting characters
    measures the wrong thing: a three-character Japanese title carries about
    as much as a six-letter English one, so a plain length test rejects names
    that are perfectly distinctive and would quietly stop matching them.

    A kana, an ideograph or a hangul syllable therefore counts double.
    Cyrillic and Greek do NOT — a letter there is a letter, the same as in
    Latin — so they keep counting one, and ASCII is unchanged.
    """
    return sum(2 if any(lo <= ord(ch) <= hi for lo, hi in _DENSE_SCRIPTS)
               else 1
               for ch in (slug or ""))


def version_insensitive_slug(name: str) -> str:
    """Lowercase alphanumeric slug with version/build tokens removed — the
    comparison key for "same game, different version suffix".

    Built on match_slug, so a game named in a non-Latin script has a key at
    all. It did not before, and the consequence was not cosmetic: this is how
    a game is matched to the cloud folder holding its backups, and an empty
    key matched nothing, so those backups could not be found. Nothing stores
    this value — every caller computes it fresh on both sides of a
    comparison — so widening it matches more without stranding anything.
    """
    return match_slug(strip_version_tokens(name or ''))


def _normalize_folder_name(name: str) -> str:
    """Sanitize folder name for filesystem."""
    import re
    name = re.sub(r'[<>:"/\\|?*]', '_', name).strip()
    if not name:
        name = "Unknown"
    return name[:128]

def get_folder_name_for_save(game_name: str, exe_path: str, game_id: str = "") -> str:
    """Get sanitized folder name for organizing backups, sync, and icons.
    
    Priority: game_name > exe parent folder (only as fallback when no game name).
    """
    from pathlib import Path
    
    # First: try game name
    name = _normalize_folder_name(game_name) if game_name else ""

    # Second: only fallback to exe parent folder if NO game name at all.
    # Some callers pass save_paths[0] in the exe_path slot — a virtual
    # registry entry there must not be Path()-parsed into a bogus folder
    # name ("Vendor" from registry:HKCU\Software\Vendor\Game).
    if not name and exe_path and not exe_path.lower().startswith("registry:"):
        parent = Path(exe_path).parent
        folder_name = parent.name
        if folder_name and parent != parent.parent:
            name = _normalize_folder_name(folder_name)
    
    # Fallback
    if not name:
        name = "Unknown"
    
    return name

def get_install_folder_name(exe_path: str, game_name: str = "", game_id: str = "", computed_folder_name: str | None = None) -> str:
    """Get sanitized folder name for organizing backups, sync, and icons.

    Uses computed_folder_name if set (stored in game entry - always recoverable).
    """
    if computed_folder_name:  # non-empty string only
        return computed_folder_name
    return get_folder_name_for_save(game_name, exe_path, game_id)
