"""
SaveSync - Core Constants
Centralized configuration to avoid hardcoding.
"""
from pathlib import Path
import logging
import os
import platform
import re
import string

logger = logging.getLogger(__name__)

# App identity
APP_NAME = "SaveSync"
APP_VERSION = "1.4.0"
APP_ID = "com.savesync.app"
GITHUB_REPO = "Luke0094/SaveSync-Your-saves-everywhere"
GITHUB_URL = f"https://github.com/{GITHUB_REPO}"
GITHUB_RELEASES_URL = f"{GITHUB_URL}/releases"
GITHUB_RELEASES_API = (
    f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
)

# Paths — platform-aware data directory
def _user_data_dir() -> Path:
    system = platform.system()
    if system == "Windows":
        return Path(os.getenv("APPDATA", str(Path.home()))) / APP_NAME
    elif system == "Darwin":
        return Path.home() / "Library" / "Application Support" / APP_NAME
    else:
        return Path(os.getenv("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))) / APP_NAME

USER_DATA_DIR = _user_data_dir()
CONFIG_FILE = USER_DATA_DIR / "config.json"
LIBRARY_FILE = USER_DATA_DIR / "library.json"
BACKUP_DIR = USER_DATA_DIR / "backups"
LOGS_DIR = USER_DATA_DIR / "logs"
CACHE_DIR = USER_DATA_DIR / "cache"
MACHINE_ID_FILE = USER_DATA_DIR / "machine_id"
CONFIG_HISTORY_DIR = USER_DATA_DIR / "config_history"

def _with_plural_list(words) -> list[str]:
    """Ordered, de-duplicated expansion of *words* with their simple English
    plural (trailing 's'), first-seen order preserved. Lets a keyword list
    name each word once instead of both forms by hand ("save" also yields
    "saves", "profile"→"profiles"); a word already ending in 's' is emitted
    unchanged. List form for call sites that iterate or extend the result."""
    out: list[str] = []
    for w in words:
        wl = (w or "").lower()
        if not wl or wl in out:
            continue
        out.append(wl)
        if not wl.endswith('s'):
            pl = wl + 's'
            if pl not in out:
                out.append(pl)
    return out


# Save detection - folders that commonly contain save data (not hardcoded,
# user can extend). Listed as singulars; the plural forms ("save"→"saves",
# "profile"→"profiles", "backup"→"backups", …) are generated by the
# trailing-s combinator so no form is ever typed twice.
SAVE_FOLDER_HINTS = _with_plural_list([
    "save", "savegame", "save_game", "savedata", "save_data",
    "gamesave", "game_save", "progress", "userdata", "user_data",
    "profile", "slot", "checkpoint", "autosave", "quicksave",
    "backup", "data",
])


# Chromium/CEF's OWN fixed internal bookkeeping folder names, inside a
# "User Data" profile tree — never a game's own data. NOT exhaustive (new
# ones get added to Chromium over time); the ones actually seen causing a
# false save-candidate. Deliberately does NOT include "Default" or any
# other PROFILE name: a profile folder legitimately holds a game's own
# subfolder for its real data (confirmed on a real Electron game — its
# saves live at "User Data/Default/<GameName>"), so excluding profile
# folders themselves would throw out real saves, not just Chromium's own
# bookkeeping.
_CHROMIUM_INTERNAL_NAMES = frozenset({
    # web-platform / per-origin storage
    "local storage", "session storage", "indexeddb", "databases",
    "file system", "shared dictionary", "cache storage", "service worker",
    "videodecodestats", "shared_proto_db", "quota",
    # caches
    "cache", "code cache", "gpucache", "shadercache", "grshadercache",
    "dawncache", "dawngraphitecache", "graphitedawncache", "dawnwebgpucache",
    "component_crx_cache", "extensions_crx_cache",
    # browser bookkeeping / telemetry / ML — both underscore and space
    # spellings kept: real Chromium releases have used both over time, and
    # a superset here can never falsely exclude a game's own folder (none
    # of these coincide with a real game title).
    "stability", "crashpad", "crash reports", "blob_storage", "sessions",
    "thumbnails", "search logos", "web applications",
    "history provider cache", "network", "download service",
    "webrtc logs", "browsermetrics", "module info cache", "widevinecdm",
    "safe browsing", "sync data", "extension rules", "extension state",
    "extension scripts", "local extension settings",
    "sync extension settings", "managed extension settings",
    "platform notifications", "feature engagement tracker",
    "site characteristics database", "autofillstrikedatabase",
    "budgetdatabase", "segmentation_platform",
    "optimization_guide_hint_cache_store",
    "optimization_guide_model_and_features_store",
    "optimization guide predictions", "affiliation database",
    "data_reduction_proxy_leveldb", "persistentorigintrials",
    "origin trials", "attributionreporting", "commerce_subscription_db",
    "subresource filter", "ssl error assistant", "variations seed",
    "pnacl",
})


def is_chromium_internal_dir(path) -> bool:
    """Whether *path* is one of Chromium/CEF's OWN internal bookkeeping
    folders ("Stability", "Crashpad", …), never a game's own data.

    A great many games embed a Chromium-based overlay, launcher or UI (CEF,
    Electron) — its "User Data" folder is real, common, and its top-level
    spelling happens to match this project's own "userdata"/"user_data"
    save-folder hint by naming coincidence. Some of Chromium's internal
    subfolders are transient too — deleted and recreated across runs,
    which reads exactly like a "save" the watcher noticed disappear.

    Matched by exact name against Chromium's own fixed vocabulary
    (_CHROMIUM_INTERNAL_NAMES), never against the whole "User Data" tree —
    a profile folder ("Default", or any other profile name) is real
    Chromium structure too, but games routinely nest their OWN save data
    a level or two inside one (confirmed on a real Electron game: its
    saves live at "User Data/Default/<GameName>"), so excluding the tree
    wholesale throws out real saves along with Chromium's bookkeeping.
    *path* can be the internal folder itself OR a file some levels inside
    it — every path component between the "User Data" root and *path* is
    checked, not just *path*'s own immediate name.

    "Local State" is the tree's own signature: every Chromium/CEF profile
    root writes it, unconditionally, so a folder that merely happens to
    share a name with one of these ("Crashpad" from something unrelated,
    say) is left alone unless it is genuinely inside such a tree.
    """
    p = Path(path)
    root = None
    for parent in p.parents:
        if parent.name.lower() == "user data" and (parent / "Local State").is_file():
            root = parent
            break
    if root is None:
        return False
    return any(part.lower() in _CHROMIUM_INTERNAL_NAMES
              for part in p.relative_to(root).parts)

# Windows paths to watch (not hardcoded; resolved at runtime)
# Covers: Unity (LocalLow), Unreal (AppData/Local + Saved), old-school (Documents),
# Steam (userdata), GOG (AppData/Roaming), Windows Store (LocalLow), etc.
WATCH_PATHS_TEMPLATES = [
    # AppData — Roaming (most Windows games: config, saves in company subfolders)
    "{APPDATA}",
    # AppData — Local (Unreal Engine "Saved" folders, many indie games)
    "{LOCALAPPDATA}",
    # AppData — LocalLow (Unity default: Application.persistentDataPath on Windows)
    "{USERPROFILE}/AppData/LocalLow",
    # Documents (classic location: EA, Rockstar, Bethesda, many others).
    # Game-specific subfolders are covered by the "My Games" root — do not
    # list individual titles here.
    "{USERPROFILE}/Documents",
    "{USERPROFILE}/Documents/My Games",
    "{USERPROFILE}/Documents/Electronic Arts",
    "{USERPROFILE}/Documents/Rockstar Games",
    # Saved Games (Windows shell folder, used by some titles)
    "{USERPROFILE}/Saved Games",
    # Steam userdata (cloud-ready saves — under steam install, but also replicated locally)
    "{LOCALAPPDATA}/Steam",
    # OneDrive synced saves
    "{USERPROFILE}/OneDrive/Documents/My Games",
    "{USERPROFILE}/OneDrive/Documents",
    # Linux / macOS equivalents resolved at runtime by _resolve_watch_paths()
]

# File extensions to skip during save scanning.
# NOTE: keep this list narrow — many games use .sav, .save, .ini, .cfg, .xml
# as their actual save format. Only skip clearly non-save content.
SKIP_EXTENSIONS = {
    ".exe", ".dll", ".so", ".pak", ".rpa",
    ".log", ".pdb", ".lib", ".obj",
    ".mp3", ".ogg", ".wav", ".flac",
    ".png", ".jpg", ".jpeg", ".bmp", ".tga", ".dds",
    ".mp4", ".avi", ".mkv",
    ".ttf", ".otf",
    ".hlsl", ".glsl", ".shader",
    ".assets", ".unity", ".unity3d",
    ".py", ".pyc", ".pyo",
    ".info", ".html", ".htm",
    ".txt",
}


def _with_simple_plural(words) -> frozenset:
    """Frozenset form of the trailing-s plural combinator (see
    _with_plural_list): "log" also covers "logs" without a separate entry.
    Used by exclusion sets that need set-membership (e.g. SKIP_FILENAME_STEMS)."""
    return frozenset(_with_plural_list(words))


# Filenames (stem only — extension ignored) that should never be detected
# or backed up as save data, regardless of their extension: a "log" file
# living next to real saves (log.txt, log.dat, or extension-less) is engine
# noise, not player data. Only the singular needs to be listed; see
# _with_simple_plural() above for the "log"/"logs" combinator.
SKIP_FILENAME_STEMS = _with_simple_plural({
    "log",
    "cache",
})

# Extensions excluded from save DETECTION only (scan scoring, live tracking,
# watcher events, auto-scan proposals). Deliberately NOT merged into the
# backup skip list: a user-confirmed save folder may legitimately contain
# .dat/.bin saves and those must keep being backed up — they just must not
# drive automatic detection, where they are overwhelmingly engine noise.
DETECTION_SKIP_EXTENSIONS = {
    ".info", ".html", ".htm", ".dat", ".bin",
}

# Machine fingerprint fields — used by machine.py to build identity hash
MACHINE_FIELDS = ["node", "processor", "machine", "system"]

# Backup fallbacks (runtime values live in config_manager._DEFAULTS)
MAX_LOCAL_BACKUPS = 6
BACKUP_RETENTION_DAYS = 30
MIN_KEPT_BACKUPS = 3


# Insert-a-space camelCase boundary ("SuperGameStory" → "Super Game Story").
# Shared by the search/query builders, the save detector and the scan dialog.
CAMEL_SPLIT_RE = r'(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])'


def strip_version_tokens(name: str) -> str:
    """Remove version/build markers and DLsite product codes from a
    game/folder name: ``v1.2``, ``V0.5.3b``, ``ver 2``, ``version 3.0``,
    ``b12``, ``build 15``, ``Build-2024.1``, ``v1,27`` (a comma sat where a
    period belongs — seen on a real release), ``[RJ123456]``/``RE``/``VJ``
    codes — these change across game updates or disappear on other
    stores while the game stays the same, so identity comparisons
    (remote backup folders, search queries) must ignore them. The code
    prefixes are the DLsite product-code family ((RJ|RE|VJ) + 4-10 digits).

    Bare numbers and roman numerals are deliberately preserved:
    "Example Game 3", "Example Game V" and "Example Game RE4" keep their
    sequel identity (version markers must be followed by digits; DLsite
    codes need at least 4 digits).
    """
    import re
    if not name:
        return name
    # (?<![a-zA-Z0-9]) instead of \b: underscores are word chars, so \b never
    # fires in names like "MyGame_v0.5_build12". The trailing
    # (?![a-zA-Z0-9]) keeps tokens whole: "V2ray" and "RJ123456abc" are
    # names, not markers; "v0.5b" (single letter suffix) is still one.
    cleaned = re.sub(
        r'[\s._\-\(\[]*(?<![a-zA-Z0-9])'
        r'(?:(?:v(?:er(?:sion)?)?|b(?:uild)?)[\s._\-]*\d+(?:[._\-,]\d+)*[a-z]?'
        r'|(?:RJ|RE|VJ)\d{4,10})'
        r'(?![a-zA-Z0-9])[\)\]]*',
        ' ', name, flags=re.IGNORECASE,
    )
    cleaned = re.sub(r'\s{2,}', ' ', cleaned).strip(' ._-')
    return cleaned or name


def strip_dlsite_code(name: str) -> str:
    """Remove a DLsite product code (RJ/RE/VJ + 4-10 digits) from *name*,
    bracketed or not — the same token strip_version_tokens already
    recognizes, isolated here for callers that want the code gone but the
    VERSION kept (strip_version_tokens's own drop_version removes both
    together; _strip_release_noise's bracket stripper only catches a
    BRACKETED code, e.g. "[RJ123456]" — an unbracketed leading one like
    "RJ123456 Some Title v1.0" sails straight through it otherwise).
    """
    import re
    if not name:
        return name
    cleaned = re.sub(
        r'[\s._\-\(\[]*(?<![a-zA-Z0-9])(?:RJ|RE|VJ)\d{4,10}(?![a-zA-Z0-9])[\)\]]*',
        ' ', name, flags=re.IGNORECASE,
    )
    cleaned = re.sub(r'\s{2,}', ' ', cleaned).strip(' ._-')
    return cleaned or name


def extract_version_token(name: str) -> str:
    """The version marker itself out of *name* — "v1.2.3" out of
    "[GOG] Some Title v1.2.3-CODEX" — or "" when none is found.

    The inverse of strip_version_tokens: that one throws the marker away
    and keeps the title; this one IS the marker, for the one place that
    wants to show the version and nothing else (not a DLsite product code
    — those identify a release, not a version, so unlike
    strip_version_tokens this deliberately doesn't match them).
    """
    import re
    if not name:
        return ""
    m = re.search(
        r'(?<![a-zA-Z0-9])((?:v(?:er(?:sion)?)?|b(?:uild)?)[\s._\-]*\d+(?:[._\-,]\d+)*[a-z]?)'
        r'(?![a-zA-Z0-9])',
        name, flags=re.IGNORECASE,
    )
    return m.group(1).strip() if m else ""


# The kana voiced/semi-voiced sound marks. Combining characters, but part of
# the letter rather than an accent on it — see match_slug.
_KANA_VOICING = ("゙", "゚")


def match_slug(name: str) -> str:
    """A name reduced to its letters and digits, for comparing two names.

    Keeps letters and digits in ANY script, which is the whole point. The
    rule this replaces was ``[^a-z0-9]`` — it deleted every character that
    was not a plain ASCII letter or digit, so a title written entirely in
    Japanese, Chinese, Korean, Russian or Greek slugged down to the empty
    string and could never be matched against the folder it saves into,
    however exactly the two names agreed.

    Accents are FOLDED rather than kept, and that is not a detail. A game
    called ``Café`` very often installs into a folder called ``Cafe``, and a
    slug that kept the accent would stop matching the two — worse than the
    rule it replaces, which at least reduced both to something shared. So
    the name is decomposed and its combining marks dropped first: ``Café``
    and ``Cafe`` both become ``cafe``. Full-width and ligature forms fold the
    same way, which is what NFKD is for.

    Japanese voicing marks are the one exception, and they have to be. A
    dakuten is a combining mark like an acute accent is, but it is not
    decoration: ``ゲ`` and ``ケ`` are different kana, the way ``b`` and ``p``
    are different letters. Dropping it with the accents would fold apart
    games that merely sound alike, so it is kept and put back.

    ASCII names come out exactly as they did before.
    """
    import unicodedata
    text = unicodedata.normalize("NFKD", (name or "").lower())
    kept = "".join(ch for ch in text
                   if ch in _KANA_VOICING or not unicodedata.combining(ch))
    return "".join(ch for ch in unicodedata.normalize("NFC", kept)
                   if ch.isalnum())


# Scripts that pack a word into far fewer characters than Latin does: the
# kana, the CJK ideographs, and the hangul syllables. Used by slug_weight.
_DENSE_SCRIPTS = (
    (0x3040, 0x30FF),   # hiragana and katakana
    (0x3400, 0x4DBF),   # CJK unified ideographs, extension A
    (0x4E00, 0x9FFF),   # CJK unified ideographs
    (0xF900, 0xFAFF),   # CJK compatibility ideographs
    (0xAC00, 0xD7AF),   # hangul syllables
)


def slug_weight(slug: str) -> int:
    """How distinctive a slug is, measured in Latin-equivalent characters.

    Every "is this name specific enough to match on?" test used to count
    characters, which was the same thing as counting Latin letters because a
    slug could not hold anything else. Now that it can, counting characters
    measures the wrong thing: a three-character Japanese title carries about
    as much as a six-letter English one, so a plain length test rejects names
    that are perfectly distinctive and would quietly stop matching them.

    A kana, an ideograph or a hangul syllable therefore counts double.
    Cyrillic and Greek do NOT — a letter there is a letter, the same as in
    Latin — so they keep counting one, and ASCII is unchanged.
    """
    return sum(2 if any(lo <= ord(ch) <= hi for lo, hi in _DENSE_SCRIPTS)
               else 1
               for ch in (slug or ""))


def version_insensitive_slug(name: str) -> str:
    """Lowercase alphanumeric slug with version/build tokens removed — the
    comparison key for "same game, different version suffix".

    Built on match_slug, so a game named in a non-Latin script has a key at
    all. It did not before, and the consequence was not cosmetic: this is how
    a game is matched to the cloud folder holding its backups, and an empty
    key matched nothing, so those backups could not be found. Nothing stores
    this value — every caller computes it fresh on both sides of a
    comparison — so widening it matches more without stranding anything.
    """
    return match_slug(strip_version_tokens(name or ''))


_TOKEN_AFTER_BOUNDARY_RE = re.compile(r'[A-Za-z0-9]+')


def _looks_like_sequel_marker(token: str) -> bool:
    """True when *token* (the word right after a matched name prefix)
    reads as a sequel/entry number rather than a subtitle — "2", "VII"
    and the like. A digit or a multi-letter roman numeral straight after
    the shared prefix means the games are related but distinct entries,
    not the same game under a grown title.

    Reuses game_sources.common's own Roman-numeral table (built for
    matching search results against sequel titles) rather than a second
    one here; imported lazily — that module imports from this one at
    load time, so a top-level import would be circular. Single-letter
    "I"/"V"/"X" are deliberately not treated as numerals here either,
    same reasoning as there: in a title they are far more often a real
    word or initial than the number 1/5/10.
    """
    if not token:
        return False
    if token.isdigit():
        return True
    from core.game_sources.common import _ROMAN_TO_ARABIC
    return token.lower() in _ROMAN_TO_ARABIC


def names_probably_same_game(a: str, b: str) -> bool:
    """True when two game NAMES (not exe paths) probably name the same
    game — either an exact match once case/whitespace is ignored, or one
    is a clean PREFIX of the other.

    The prefix case is for a title that grew between releases: an early
    build tracked in the library under a short working title, a later one
    under its full release title with a subtitle appended.
    strip_version_tokens already handles a trailing VERSION growing; this
    handles the TITLE itself growing, which is a different kind of change
    and needs a different check.

    Deliberately checked on the raw names, not on version_insensitive_slug
    — slugging strips every space and punctuation mark, and a slug prefix
    check on THAT would happily match two names that only share a leading
    run of letters, with no word boundary left to say otherwise. Checked
    here on the lowercased names themselves instead, so the character
    right after the shorter name can be required to be a real boundary
    (space, dash, …), not another letter. A shorter name under 3
    characters is never trusted alone — too little to be real evidence
    either way.

    A prefix match is also rejected when the word immediately following
    the shared prefix is a bare number or a short roman numeral (e.g. the
    shorter name is "Game" and the longer is "Game 2" / "Game II") —
    that shape names a SEQUEL, a distinct entry in a series, not the same
    game grown a subtitle.
    """
    a_norm = (a or '').strip().lower()
    b_norm = (b or '').strip().lower()
    if not a_norm or not b_norm:
        return False
    if a_norm == b_norm:
        return True
    shorter, longer = (a_norm, b_norm) if len(a_norm) <= len(b_norm) else (b_norm, a_norm)
    if len(shorter) < 3 or not longer.startswith(shorter):
        return False
    boundary = longer[len(shorter):len(shorter) + 1]
    if boundary.isalnum():
        return False
    remainder = longer[len(shorter):].lstrip(string.whitespace + string.punctuation)
    next_token = _TOKEN_AFTER_BOUNDARY_RE.match(remainder)
    if next_token and _looks_like_sequel_marker(next_token.group(0)):
        return False
    return True


# Separator between a name and the tag that distinguishes it from another
# name spelled the same way. Survives _normalize_folder_name (which only
# rewrites <>:"/\|?* ) and is dropped by match_slug, so a tagged name shares
# no comparison key with anything else.
_DISAMBIGUATION_MARK = "~"


def disambiguate_name(base: str, taken, hint: str = "") -> str:
    """*base*, or *base* plus a generic tag when *taken* already holds it.

    Explicitly NOT ``base_2``. A trailing number is how a sequel is written,
    and the comparison key this whole codebase matches names by cannot tell
    the two apart: strip_version_tokens deliberately KEEPS bare numbers, so
    that "Example Game 3" stays a different game from "Example Game" — which
    means the ``MyGame_2`` minted for a mere name collision reduces to
    exactly the slug a genuine "MyGame 2" reduces to. A disambiguator that
    collides with a real sequel is not doing its job, and to the person
    reading a list of folders it simply looks like the second chapter of
    something. ``MyGame~4f2a91`` can be neither.

    The tag comes from *hint* — the thing being named, normally its source
    path — rather than from a counter, which makes it STABLE as well as
    generic: naming the same thing twice lands on the same name instead of
    climbing _2, _3, _4 on every attempt. Without a hint, or if the derived
    tag is somehow taken too, it falls back to random; still generic, just
    not repeatable.

    *taken* is any container of already-used names; the comparison is
    case-insensitive, so pass casefolded values.
    """
    import hashlib
    import uuid
    if not base:
        return base
    used = {str(x).casefold() for x in (taken or ())}
    if base.casefold() not in used:
        return base
    if hint:
        token = hashlib.sha1(str(hint).casefold().encode("utf-8", "replace")).hexdigest()[:6]
        candidate = f"{base}{_DISAMBIGUATION_MARK}{token}"
        if candidate.casefold() not in used:
            return candidate
    while True:
        candidate = f"{base}{_DISAMBIGUATION_MARK}{uuid.uuid4().hex[:6]}"
        if candidate.casefold() not in used:
            return candidate
        if len(used) > 1000:
            logger.warning("disambiguate_name: exhausted %d candidates for %r", len(used), base)
            return candidate


def strip_disambiguation_tag(name: str) -> str:
    """*name* with a tag disambiguate_name may have appended taken back off.

    The inverse of disambiguate_name, and it has to exist as a pair with it:
    anything that GROUPS names spelled the same way — "how many cloud folders
    are there for this title" — has to undo the distinguishing tag first, and
    doing that with an inline regex somewhere else is how the two drift apart.

    Both spellings are accepted, because both exist on disk: the ``~<hex>``
    this mints now, and the historical ``_2`` / ``_3`` that folders created by
    earlier versions still carry.
    """
    import re
    if not name:
        return name
    return re.sub(r"(?:" + re.escape(_DISAMBIGUATION_MARK) + r"[0-9a-f]{4,12}|_\d+)$",
                  "", str(name))


def _normalize_folder_name(name: str) -> str:
    """Sanitize folder name for filesystem."""
    import re
    name = re.sub(r'[<>:"/\\|?*]', '_', name).strip()
    if not name:
        name = "Unknown"
    return name[:128]

def get_folder_name_for_save(game_name: str, exe_path: str, game_id: str = "") -> str:
    """Get sanitized folder name for organizing backups, sync, and icons.
    
    Priority: game_name > exe parent folder (only as fallback when no game name).
    """
    from pathlib import Path
    
    # First: try game name
    name = _normalize_folder_name(game_name) if game_name else ""

    # Second: only fallback to exe parent folder if NO game name at all.
    # Some callers pass save_paths[0] in the exe_path slot — a virtual
    # registry entry there must not be Path()-parsed into a bogus folder
    # name ("Vendor" from registry:HKCU\Software\Vendor\Game).
    if not name and exe_path and not exe_path.lower().startswith("registry:"):
        parent = Path(exe_path).parent
        folder_name = parent.name
        if folder_name and parent != parent.parent:
            name = _normalize_folder_name(folder_name)
    
    # Fallback
    if not name:
        name = "Unknown"
    
    return name

def get_install_folder_name(exe_path: str, game_name: str = "", game_id: str = "", computed_folder_name: str | None = None) -> str:
    """Get sanitized folder name for organizing backups, sync, and icons.

    Uses computed_folder_name if set (stored in game entry - always recoverable).
    """
    if computed_folder_name:  # non-empty string only
        return computed_folder_name
    return get_folder_name_for_save(game_name, exe_path, game_id)
